In [9]:
import pandas as pd

In [10]:
df = pd.read_csv("brooklyn_sales_map.csv")
df

/home/nikita/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (40,41,43,45,46,47,86) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Unnamed: 0,borough,neighborhood,building_class_category,tax_class,block,lot,easement,building_class,address,...,EDesigNum,APPBBL,APPDate,PLUTOMapID,FIRM07_FLA,PFIRM15_FL,Version,MAPPLUTO_F,SHAPE_Leng,SHAPE_Area
0,1,3,DOWNTOWN-METROTECH,28 COMMERCIAL CONDOS,4,140,1001,NaN,R5,330 JAY STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,3,DOWNTOWN-FULTON FERRY,29 COMMERCIAL GARAGES,4,54,1,NaN,G7,85 JAY STREET,...,NaN,3.000540e+09,12/06/2002,1.0,NaN,NaN,17V1.1,0.0,1559.889144,140131.577176
2,3,3,BROOKLYN HEIGHTS,21 OFFICE BUILDINGS,4,204,1,NaN,O6,29 COLUMBIA HEIGHTS,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,890.718521,34656.447240
3,4,3,MILL BASIN,22 STORE BUILDINGS,4,8470,55,NaN,K6,5120 AVENUE U,...,NaN,0.000000e+00,NaN,1.0,1.0,1.0,17V1.1,0.0,3729.786857,797554.847834
4,5,3,BROOKLYN HEIGHTS,26 OTHER HOTELS,4,230,1,NaN,H8,21 CLARK STREET,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,620.761169,21360.147631
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390878,390879,3,WYCKOFF HEIGHTS,31 COMMERCIAL VACANT LAND,1,3337,19,NaN,C0,364 LINDEN STREET,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,244.422014,2501.088819
390879,390880,3,WYCKOFF HEIGHTS,31 COMMERCIAL VACANT LAND,1,3337,19,NaN,C0,364 LINDEN STREET,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,244.422014,2501.088819
390880,390881,3,WYCKOFF HEIGHTS,41 TAX CLASS 4 - OTHER,4,3280,50,NaN,Z9,383 HARMAN STREET,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,231.409296,2795.673780
390881,390882,3,3004,04 TAX CLASS 1 CONDOS,NaN,6886,1107,NaN,NaN,14 BAY 47TH STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
390882,390883,3,3004,04 TAX CLASS 1 CONDOS,NaN,6886,1109,NaN,NaN,14 BAY 47 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df = df.drop(df.columns[0], axis=1)

In [13]:
df = df.drop_duplicates(keep='first')

In [17]:
from sklearn import preprocessing

In [18]:
le_neighborhood = preprocessing.LabelEncoder()
le_neighborhood.fit(df["neighborhood"])
df["neighborhood"] = le.transform(df["neighborhood"])

In [24]:
t = pd.options.display.max_rows
pd.options.display.max_rows = 150
print(df.dtypes)
pd.options.display.max_rows = t

borough                      int64
neighborhood                 int64
building_class_category     object
tax_class                   object
block                        int64
lot                          int64
easement                   float64
building_class              object
address                     object
apartment_number            object
zip_code                     int64
residential_units            int64
commercial_units             int64
total_units                  int64
land_sqft                  float64
gross_sqft                 float64
year_built                   int64
tax_class_at_sale            int64
building_class_at_sale      object
sale_price                 float64
sale_date                   object
year_of_sale                 int64
Borough                     object
CD                         float64
CT2010                     float64
CB2010                     float64
SchoolDist                 float64
Council                    float64
ZipCode                    float64
FireComp                    object
PolicePrct                 float64
HealthCent                 float64
HealthArea                 float64
SanitBoro                  float64
SanitDistr                 float64
SanitSub                    object
Address                     object
ZoneDist1                   object
ZoneDist2                   object
ZoneDist3                   object
ZoneDist4                   object
Overlay1                    object
Overlay2                    object
SPDist1                     object
SPDist2                     object
SPDist3                     object
LtdHeight                   object
SplitZone                   object
BldgClass                   object
LandUse                    float64
Easements                  float64
OwnerType                   object
OwnerName                   object
LotArea                    float64
BldgArea                   float64
ComArea                    float64
ResArea                    float64
OfficeArea                 float64
RetailArea                 float64
GarageArea                 float64
StrgeArea                  float64
FactryArea                 float64
OtherArea                  float64
AreaSource                 float64
NumBldgs                   float64
NumFloors                  float64
UnitsRes                   float64
UnitsTotal                 float64
LotFront                   float64
LotDepth                   float64
BldgFront                  float64
BldgDepth                  float64
Ext                         object
ProxCode                   float64
IrrLotCode                  object
LotType                    float64
BsmtCode                   float64
AssessLand                 float64
AssessTot                  float64
ExemptLand                 float64
ExemptTot                  float64
YearBuilt                  float64
YearAlter1                 float64
YearAlter2                 float64
HistDist                    object
Landmark                    object
BuiltFAR                   float64
ResidFAR                   float64
CommFAR                    float64
FacilFAR                   float64
BoroCode                   float64
BBL                        float64
CondoNo                    float64
Tract2010                  float64
XCoord                     float64
YCoord                     float64
ZoneMap                     object
ZMCode                      object
Sanborn                     object
TaxMap                     float64
EDesigNum                   object
APPBBL                     float64
APPDate                     object
PLUTOMapID                 float64
FIRM07_FLA                 float64
PFIRM15_FL                 float64
Version                     object
MAPPLUTO_F                 float64
SHAPE_Leng                 float64
SHAPE_Area                 float64
dtype: object